CREATE TABLE [dbo].[tblUser]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Username] VARCHAR(255) NOT NULL,
    [Password] VARCHAR(255) NOT NULL,
    [Email] VARCHAR(255) NOT NULL UNIQUE,
	[FirstName] VARCHAR(255) NOT NULL,
	[LastName] VARCHAR(255) NOT NULL,
)